name: periodic-analyze

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 1'
jobs:
  periodic-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: analyze
        run: python3 analyze.py
      - name: push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email ""
          git add .
          git diff-index --quiet HEAD || git commit -m "periodic analysis"
          git push
