name: periodic-analyze

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *' # This cron expression runs at midnight every 7 days

jobs:
  periodic-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: analyze
        run: python3 analyze.py
      - name: push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email ""
          git add .
          git diff-index --quiet HEAD || git commit --amend --no-edit
          git push --force
